### ISSUE TITLE
Train detail.

### ISSUE THREAD

**Issue by ElephantGit** [SeongjinPark/RDFNet#4]
Do you train your network with this nyud_layers.py?
When I train your network on scannet dataset, the output of your network is 116x156, it is not same as label size(100x100)? They don't match, so I get this error: math_functions.cu:174] Check failed: status == CUBLAS_STATUS_SUCCESS (11 vs. 0)  CUBLAS_STATUS_MAPPING_ERROR. What should I do?

My data is scannet_frames_25k which is download from ScanNet dataset, The resolution of input color image is 1296x968, the resolution of input label is 1296x968, too. However, the resolution of input hha is 640x480, so I down-sample the color and label to 640x480 in nyud_layers.py.

**Comment by SeongjinPark** [comment]
To remove the white boundaries of NYUD images, I crop the original image slightly as it is written in the nyud_layers.py
And then, the output will be 4 times smaller than the original image due to pooling operations. 
You should consider it when you train a model on your own data.
