### ISSUE TITLE
Test Questions

### ISSUE THREAD

**Issue by qinfeiyu19941208** [SeongjinPark/RDFNet#5]
Thank you very much for providing code of RDFNet.
After looking at your code, I still have some questions.
1) What is the average BGR subtracted from the test?
 self.mean_bgr = np.array((116.190, 97.203, 92.318), dtype=np.float32)
 or
 self.mean_bgr = np.array((128.0, 128.0, 128.0), dtype=np.float32)
2) Your test is on the resolution of 560*425 or 640*480 ? Because Gupta provides a NYU_v2 data set that images' resolution is 560*425, but your papar's qualitative results seem the resolution is 640*480.
3) How does multi-scale result fusion operate when network prediction occurs? Averaging on final score map of averaging on score map after softmax layer?
4)I'm sorry I can't reach the accuracy of your announcemnet. Could you provide code of multi-scale evaluation and test code? 
Thank you for your sharing.

**Comment by SeongjinPark** [comment]
Sorry for late reply. I've been busy doing my work since I graduated. 
1. I simply used 128.128.128.
2. I used 640 480 images for fair comparison with the RefineNet paper. Original size of images are also provided in the NYUDv2. Following the advice of authors of RefineNet, I shaved the white borders in the original images.
3. After upsampling the scoremaps by 4 times, averaged final outputs after softmax layer.
Thank you for your interest.

**Comment by qinfeiyu19941208** [comment]
Thank you for your reply. some other questions.
1) Are your quantitative indicators done at 640*480 resolution?
2) multi-scale inputs  will output score maps of different resolution. How did you deal with it?
3) the test prototxt you provide did not have softmax  layer in the end？So, I need to add a softmax layer
to get the final result?

**Comment by SeongjinPark** [comment]
1. Yes.
2. Just resize the outputs.
3. Oh, my mistake. I simply summed the scoremaps and used the label corresponding to the largest value.

**Comment by qinfeiyu19941208** [comment]
Tnank you.
3. I know the sofrtmax did not affect the result of classification labels. But when you average the prediction, the feaure map size is not [0,1] may couse some problems that one scale score map 
occupies a dominant position. It is theoretically necessary to normalize before weighting.

**Comment by SeongjinPark** [comment]
Sorry, I answered wrongly because it was the work of two years ago XD. I modified the previous answer. Thank you again.

**Comment by qinfeiyu19941208** [comment]
Thank you for your reply. It is an Interesting work.
